### ISSUE TITLE
wrong enable JS id/label

### ISSUE THREAD

**Issue by helmixx** [peixotorms/fast-velocity-minify#1]
hej raul.
thanks for your supperb plugin! i loved it in the former (2) version and i do love the new version (3) even more! :)
i just found a little piece of wrong declaration/naming of a id/label …
in JS Settings the first label for the input uses 'fvm_settings_css_enable' (a second time), what result in an unexpected jump/action with some browsers when not hitting the input nexactly.
best,
s

**Comment by peixotorms** [comment]
Thank you very much, will fix asap!
