### ISSUE TITLE
FVM_DIR constant can't be used to change cache location

### ISSUE THREAD

**Issue by carl-alberto** [peixotorms/fast-velocity-minify#7]
Hi @peixotorms ,

First of all, awesome plugin you have here but it seems overriding the cache location to the common dynamic writable path of WordPress in wp-content/uploads via `FVM_DIR` is not working. That override is useful especially on a version-controlled codebase but the documented override by the plugin does not work when using the `FVM_DIR`is used in the plugin 
to also reference the plugin path https://github.com/peixotorms/fast-velocity-minify/blob/f2dc31229eac0f68f7ce49a6a2927d9fc656b59d/fvm.php#L38-L44 resulting to a fatal error when enabling the plugin:

example when using `define( 'FVM_DIR', 'wp-content/uploads/' );`

```
Fatal error: require_once(): Failed opening required 'wp-content/uploads/inc/common.php' (include_path='.:/usr/share/pear:/usr/share/php') in wp-content/plugins/fast-velocity-minify/fvm.php on line 47
```

Steps to reproduce:

1. Add in the wp-config.php

```
define( 'FVM_DIR', '/code/wp-content/uploads/' );
define( 'FVM_URL', WP_SITEURL . '/wp-content/uploads/' );
```  
2. By enabling the plugin, you will get the error above

Proposal:
Add in the ` function fvm_get_cache_location()` a specific CONSTANT that references the specific cache path but is also not used to reference the plugin path https://github.com/peixotorms/fast-velocity-minify/blob/f2dc31229eac0f68f7ce49a6a2927d9fc656b59d/fvm.php#L38-L44 example using `FVM_CACHE_DIR` & `FVM_CACHE_URL`

```
	if (defined('FVM_CACHE_DIR') && defined('FVM_CACHE_URL')){
	
		# define paths and url
		$sep = DIRECTORY_SEPARATOR;
		$dir = trim(rtrim(FVM_CACHE_DIR, '/\\')). $sep . 'cache' . $sep . 'fvm'. $sep . 'min';
		$durl = trim(rtrim(FVM_CACHE_URL, '/')). '/cache/fvm/min';
		
		# create and return
		if(!is_dir($dir) && function_exists('wp_mkdir_p')) { wp_mkdir_p($dir); }
		return array('ch_dir'=>$dir,'ch_url'=>$durl);
		
	}
```

**Comment by carl-alberto** [comment]
Also opened a wp.org support ticket regarding this https://wordpress.org/support/topic/fvm_dir-constant-cant-be-used-to-change-cache-location

**Comment by peixotorms** [comment]
Thank you for reporting. 
I will push an update shortly, so please use `FVM_CACHE_DIR` and `FVM_CACHE_URL` from now on.
Also note that `FVM_CACHE_DIR` requires an absolute path, not a relative one.
Thanks

**Comment by carl-alberto** [comment]
Awesome, thanks for the reply and looking forward for the next update
